name: Traffic Monitor

on:
  workflow_dispatch:

jobs:
  monitor-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Check if current time is within allowed windows
        id: time_check
        run: |
          UTC_HOUR=$(date -u +'%H')
          UTC_MINUTE=$(date -u +'%M')
          UTC_TOTAL_MINUTES=$((10#$UTC_HOUR * 60 + 10#$UTC_MINUTE))

          START1=$((3 * 60 + 30))
          END1=$((5 * 60 + 30))
          START2=$((7 * 60 + 30))
          END2=$((10 * 60 + 30))
          START3=$((13 * 60))
          END3=$((15 * 60 + 30))

          should_commit="false"
          if (( UTC_TOTAL_MINUTES >= START1 && UTC_TOTAL_MINUTES <= END1 )); then
            should_commit="true"
          elif (( UTC_TOTAL_MINUTES >= START2 && UTC_TOTAL_MINUTES <= END2 )); then
            should_commit="true"
          elif (( UTC_TOTAL_MINUTES >= START3 && UTC_TOTAL_MINUTES <= END3 )); then
            should_commit="true"
          fi

          echo "should_commit=${should_commit}" >> $GITHUB_OUTPUT

      - name: Run traffic monitor
        if: steps.time_check.outputs.should_commit == 'true'
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: node trafficmonitor.js

      - name: Commit and push if log updated
        if: steps.time_check.outputs.should_commit == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add traffic-log.json
          if ! git diff --cached --quiet; then
            git commit -m "Update traffic log - $(date -u)"
            git pull --rebase
            git push
          fi
